# Generated by Django 4.0.4 on 2024-11-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactModel',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField(max_length=2000)),
                ('contact_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'contact_details',
            },
        ),
    ]
